### PR TITLE
src: skip lws between `connection` values

### PR DESCRIPTION
**Pull request by indutny**
Fix https://github.com/iojs/io.js/issues/588

cc @bnoordhuis

### CODE REVIEW

**Comment by bnoordhuis** [comment]
LGTM with the nit that RFC 2616 allows multi-line continuations like `Upgrade: \n keep-alive`.  Perhaps you can address that in a follow-up PR, I'll leave that up to you.  This PR is already strictly an improvement, no reason not to land it.

**Comment by indutny** [comment]
I thought this behavior was deprecated in the last http 1.1 rfc, wasn't it?

**Comment by bnoordhuis** [comment]
I think - more correctly: I fear - there is no such thing as 'deprecated' when it comes to popular protocols.

**Comment by indutny** [comment]
@bnoordhuis anyway, it should be working, AFAIK. Take a look at the test above ^

**Comment by indutny** [comment]
@bnoordhuis : ping ;)

**Comment by bnoordhuis** [comment]
@indutny It still doesn't handle the `Upgrade: \n keep-alive` case, does it?  But like I said, it's already an improvement, so LGTM.

**Comment by indutny** [comment]
Landed in 59569f2125211ed7ce4163f34d0cc6f4b6801f1c, thank you!

**Pull request closed without merging**
