### PR TITLE
header: fix field sizes

### LINKED ISSUE #218: on_headers_complete handling is broken
Returning '1' from on_headers_complete is supposed to skip body processing, but it doesn't, since "F_SKIPBODY = 1 << 6" doesn't fit into 6-bit "unsigned int flags:6".

### PR DESCRIPTION
**Pull request by indutny**
Fix #218

cc @bnoordhuis

### CODE REVIEW

**Comment by bnoordhuis** [comment]
LGTM but maybe say 'use unused bits' instead of 'fix' in the commit log.

**Comment by indutny** [comment]
@bnoordhuis take a look at #218, flags do not fit the field anymore.

**Comment by bnoordhuis** [comment]
Alright then, can you update the commit log with an explanation of the fix? :-)

**Comment by indutny** [comment]
Landed in 7ba3123, thank you!

**Pull request closed without merging**
